/**
 * WorkTimeTracker.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectStatus } from '../models/ProjectStatus';
import { HttpFile } from '../http/http';

export class CreateProjectCommand {
    'name': string;
    'description'?: string | null;
    'startDate'?: Date | null;
    'endDate'?: Date | null;
    'status'?: ProjectStatus;
    'teamId'?: number | null;
    'managerId': string;
    'memberIds'?: Array<string> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ProjectStatus",
            "format": ""
        },
        {
            "name": "teamId",
            "baseName": "teamId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "managerId",
            "baseName": "managerId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "memberIds",
            "baseName": "memberIds",
            "type": "Array<string>",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return CreateProjectCommand.attributeTypeMap;
    }

    public constructor() {
    }
}


