/**
 * WorkTimeTracker.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestStatus } from '../models/RequestStatus';
import { RequestType } from '../models/RequestType';
import { HttpFile } from '../http/http';

export class LeaveRequestMinimalDto {
    'id': number;
    'date': Date;
    'requestType': RequestType;
    'reason': string;
    'status': RequestStatus;
    'createdAt': Date;
    'breakStartDate': Date;
    'breakEndDate': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "requestType",
            "baseName": "requestType",
            "type": "RequestType",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "RequestStatus",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "breakStartDate",
            "baseName": "breakStartDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "breakEndDate",
            "baseName": "breakEndDate",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return LeaveRequestMinimalDto.attributeTypeMap;
    }

    public constructor() {
    }
}


