/**
 * WorkTimeTracker.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NotificationDto } from '../models/NotificationDto';
import { HttpFile } from '../http/http';

export class NotificationDtoCursorPaginated {
    'data': Array<NotificationDto>;
    'lastId'?: number | null;
    'limit': number;
    'totalCount': number;
    'hasMore': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<NotificationDto>",
            "format": ""
        },
        {
            "name": "lastId",
            "baseName": "lastId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "hasMore",
            "baseName": "hasMore",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NotificationDtoCursorPaginated.attributeTypeMap;
    }

    public constructor() {
    }
}
