/**
 * Timesheet.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PagedRequest {
    'pageNumber'?: number;
    'pageSize'?: number;
    'searchString'?: string | null;
    'orderBy'?: Array<string> | null;
    'orderByString'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pageNumber",
            "baseName": "pageNumber",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "searchString",
            "baseName": "searchString",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderBy",
            "baseName": "orderBy",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "orderByString",
            "baseName": "orderByString",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PagedRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
