/**
 * WorkTimeTracker.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum RequestType {
    TimesheetAdjustmentRequest = 'TIMESHEET_ADJUSTMENT_REQUEST',
    LeaveRequest = 'LEAVE_REQUEST',
    OvertimeRequest = 'OVERTIME_REQUEST',
    WorkFromHomeRequest = 'WORK_FROM_HOME_REQUEST'
}
