/**
 * WorkTimeTracker.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LeaveRequestDto } from '../models/LeaveRequestDto';
import { TimesheetRequestDto } from '../models/TimesheetRequestDto';
import { HttpFile } from '../http/http';

/**
 * @type TimesheetMinimalDtoRequestsInner
 * Type
 * @export
 */
export type TimesheetMinimalDtoRequestsInner = LeaveRequestDto | TimesheetRequestDto;

/**
* @type TimesheetMinimalDtoRequestsInnerClass
* @export
*/
export class TimesheetMinimalDtoRequestsInnerClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

