/**
 * WorkTimeTracker.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LeaveRequestMinimalDto } from '../models/LeaveRequestMinimalDto';
import { RequestDto } from '../models/RequestDto';
import { TimesheetRequestMinimalDto } from '../models/TimesheetRequestMinimalDto';
import { HttpFile } from '../http/http';

/**
 * @type TimesheetDtoRequestsInner
 * Type
 * @export
 */
export type TimesheetDtoRequestsInner = LeaveRequestMinimalDto | RequestDto | TimesheetRequestMinimalDto;

/**
* @type TimesheetDtoRequestsInnerClass
* @export
*/
export class TimesheetDtoRequestsInnerClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


