/**
 * WorkTimeTracker.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TeamMinimalDto } from '../models/TeamMinimalDto';
import { UserDetailDto } from '../models/UserDetailDto';
import { UserMinimalDto } from '../models/UserMinimalDto';
import { UserPosition } from '../models/UserPosition';
import { UserStatus } from '../models/UserStatus';
import { WorkTimeDto } from '../models/WorkTimeDto';
import { HttpFile } from '../http/http';

export class UserFullDto {
    'id': string;
    'email': string;
    'fullName': string;
    'phoneNumber'?: string | null;
    'image'?: string | null;
    'userPosition': UserPosition;
    'userStatus': UserStatus;
    'isFirstLogin': boolean;
    'leaveHours': number;
    'createdAt': Date;
    'updatedAt'?: Date | null;
    'createdBy'?: string | null;
    'lastModifiedBy'?: string | null;
    'roles'?: Array<string> | null;
    'workTime'?: WorkTimeDto;
    'supervisor'?: UserMinimalDto;
    'team'?: TeamMinimalDto;
    'userDetail'?: UserDetailDto;
    'managerTeams'?: Array<TeamMinimalDto> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "fullName",
            "baseName": "fullName",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string",
            "format": ""
        },
        {
            "name": "userPosition",
            "baseName": "userPosition",
            "type": "UserPosition",
            "format": ""
        },
        {
            "name": "userStatus",
            "baseName": "userStatus",
            "type": "UserStatus",
            "format": ""
        },
        {
            "name": "isFirstLogin",
            "baseName": "isFirstLogin",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "leaveHours",
            "baseName": "leaveHours",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastModifiedBy",
            "baseName": "lastModifiedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "workTime",
            "baseName": "workTime",
            "type": "WorkTimeDto",
            "format": ""
        },
        {
            "name": "supervisor",
            "baseName": "supervisor",
            "type": "UserMinimalDto",
            "format": ""
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "TeamMinimalDto",
            "format": ""
        },
        {
            "name": "userDetail",
            "baseName": "userDetail",
            "type": "UserDetailDto",
            "format": ""
        },
        {
            "name": "managerTeams",
            "baseName": "managerTeams",
            "type": "Array<TeamMinimalDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserFullDto.attributeTypeMap;
    }

    public constructor() {
    }
}


