/**
 * WorkTimeTracker.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserDetailDto {
    'id': number;
    'birthDate'?: Date;
    'phone'?: string | null;
    'gender'?: boolean;
    'permanentAddress'?: string | null;
    'contactAddress'?: string | null;
    'yearsOfWork': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "birthDate",
            "baseName": "birthDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "permanentAddress",
            "baseName": "permanentAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "contactAddress",
            "baseName": "contactAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "yearsOfWork",
            "baseName": "yearsOfWork",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return UserDetailDto.attributeTypeMap;
    }

    public constructor() {
    }
}
