/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDeviceCategoryCommand,
  DeviceCategoryDetailsDto,
  DeviceCategoryDetailsDtoPaginated,
  ErrorResponse,
  ErrorValidateResponse,
  PagedRequest,
} from '../models/index';
import {
    CreateDeviceCategoryCommandFromJSON,
    CreateDeviceCategoryCommandToJSON,
    DeviceCategoryDetailsDtoFromJSON,
    DeviceCategoryDetailsDtoToJSON,
    DeviceCategoryDetailsDtoPaginatedFromJSON,
    DeviceCategoryDetailsDtoPaginatedToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ErrorValidateResponseFromJSON,
    ErrorValidateResponseToJSON,
    PagedRequestFromJSON,
    PagedRequestToJSON,
} from '../models/index';

export interface DeviceCategoryCreateRequest {
    createDeviceCategoryCommand?: CreateDeviceCategoryCommand;
}

export interface DeviceCategoryDeleteRequest {
    id: number;
}

export interface DeviceCategoryGetAllRequest {
    ids?: Array<number>;
}

export interface DeviceCategoryGetByIdRequest {
    id: number;
}

export interface DeviceCategorySearchRequest {
    pagedRequest?: PagedRequest;
}

export interface DeviceCategoryUpdateRequest {
    id: number;
    createDeviceCategoryCommand?: CreateDeviceCategoryCommand;
}

/**
 * 
 */
export class DeviceCategoryApi extends runtime.BaseAPI {

    /**
     */
    async deviceCategoryCreateRaw(requestParameters: DeviceCategoryCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceCategoryDetailsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/device-categories`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDeviceCategoryCommandToJSON(requestParameters['createDeviceCategoryCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceCategoryDetailsDtoFromJSON(jsonValue));
    }

    /**
     */
    async deviceCategoryCreate(requestParameters: DeviceCategoryCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceCategoryDetailsDto> {
        const response = await this.deviceCategoryCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deviceCategoryDeleteRaw(requestParameters: DeviceCategoryDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deviceCategoryDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/device-categories/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deviceCategoryDelete(requestParameters: DeviceCategoryDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deviceCategoryDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deviceCategoryGetAllRaw(requestParameters: DeviceCategoryGetAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DeviceCategoryDetailsDto>>> {
        const queryParameters: any = {};

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/device-categories`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DeviceCategoryDetailsDtoFromJSON));
    }

    /**
     */
    async deviceCategoryGetAll(requestParameters: DeviceCategoryGetAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DeviceCategoryDetailsDto>> {
        const response = await this.deviceCategoryGetAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deviceCategoryGetByIdRaw(requestParameters: DeviceCategoryGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceCategoryDetailsDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deviceCategoryGetById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/device-categories/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceCategoryDetailsDtoFromJSON(jsonValue));
    }

    /**
     */
    async deviceCategoryGetById(requestParameters: DeviceCategoryGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceCategoryDetailsDto> {
        const response = await this.deviceCategoryGetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deviceCategorySearchRaw(requestParameters: DeviceCategorySearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceCategoryDetailsDtoPaginated>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/device-categories/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PagedRequestToJSON(requestParameters['pagedRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceCategoryDetailsDtoPaginatedFromJSON(jsonValue));
    }

    /**
     */
    async deviceCategorySearch(requestParameters: DeviceCategorySearchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceCategoryDetailsDtoPaginated> {
        const response = await this.deviceCategorySearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deviceCategoryUpdateRaw(requestParameters: DeviceCategoryUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceCategoryDetailsDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deviceCategoryUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/device-categories/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDeviceCategoryCommandToJSON(requestParameters['createDeviceCategoryCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceCategoryDetailsDtoFromJSON(jsonValue));
    }

    /**
     */
    async deviceCategoryUpdate(requestParameters: DeviceCategoryUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceCategoryDetailsDto> {
        const response = await this.deviceCategoryUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
