/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateWorkScheduleCommand,
  ErrorResponse,
  ErrorValidateResponse,
  PagedRequest,
  WorkScheduleDto,
  WorkScheduleDtoPaginated,
} from '../models/index';
import {
    CreateWorkScheduleCommandFromJSON,
    CreateWorkScheduleCommandToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ErrorValidateResponseFromJSON,
    ErrorValidateResponseToJSON,
    PagedRequestFromJSON,
    PagedRequestToJSON,
    WorkScheduleDtoFromJSON,
    WorkScheduleDtoToJSON,
    WorkScheduleDtoPaginatedFromJSON,
    WorkScheduleDtoPaginatedToJSON,
} from '../models/index';

export interface WorkScheduleCreateRequest {
    createWorkScheduleCommand?: CreateWorkScheduleCommand;
}

export interface WorkScheduleDeleteRequest {
    id: number;
}

export interface WorkScheduleGetAllRequest {
    ids?: Array<number>;
}

export interface WorkScheduleGetByIdRequest {
    id: number;
}

export interface WorkScheduleSearchRequest {
    pagedRequest?: PagedRequest;
}

export interface WorkScheduleUpdateRequest {
    id: number;
    createWorkScheduleCommand?: CreateWorkScheduleCommand;
}

/**
 * 
 */
export class WorkScheduleApi extends runtime.BaseAPI {

    /**
     */
    async workScheduleCreateRaw(requestParameters: WorkScheduleCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkScheduleDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/work-schedule`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkScheduleCommandToJSON(requestParameters['createWorkScheduleCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkScheduleDtoFromJSON(jsonValue));
    }

    /**
     */
    async workScheduleCreate(requestParameters: WorkScheduleCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkScheduleDto> {
        const response = await this.workScheduleCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async workScheduleDeleteRaw(requestParameters: WorkScheduleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workScheduleDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/work-schedule/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workScheduleDelete(requestParameters: WorkScheduleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workScheduleDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async workScheduleGetAllRaw(requestParameters: WorkScheduleGetAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkScheduleDto>>> {
        const queryParameters: any = {};

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/work-schedule`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkScheduleDtoFromJSON));
    }

    /**
     */
    async workScheduleGetAll(requestParameters: WorkScheduleGetAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkScheduleDto>> {
        const response = await this.workScheduleGetAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async workScheduleGetByIdRaw(requestParameters: WorkScheduleGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkScheduleDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workScheduleGetById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/work-schedule/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkScheduleDtoFromJSON(jsonValue));
    }

    /**
     */
    async workScheduleGetById(requestParameters: WorkScheduleGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkScheduleDto> {
        const response = await this.workScheduleGetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async workScheduleSearchRaw(requestParameters: WorkScheduleSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkScheduleDtoPaginated>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/work-schedule/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PagedRequestToJSON(requestParameters['pagedRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkScheduleDtoPaginatedFromJSON(jsonValue));
    }

    /**
     */
    async workScheduleSearch(requestParameters: WorkScheduleSearchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkScheduleDtoPaginated> {
        const response = await this.workScheduleSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async workScheduleUpdateRaw(requestParameters: WorkScheduleUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkScheduleDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workScheduleUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/work-schedule/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkScheduleCommandToJSON(requestParameters['createWorkScheduleCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkScheduleDtoFromJSON(jsonValue));
    }

    /**
     */
    async workScheduleUpdate(requestParameters: WorkScheduleUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkScheduleDto> {
        const response = await this.workScheduleUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
