/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IIonCalendarOutline: typeof import('~icons/ion/calendar-outline.jsx')['default']
  const IIonCheckmark: typeof import('~icons/ion/checkmark.jsx')['default']
  const IIonClock: typeof import('~icons/ion/clock.jsx')['default']
  const IIonCubeOutline: typeof import('~icons/ion/cube-outline.jsx')['default']
  const IIonDocumentsOutline: typeof import('~icons/ion/documents-outline.jsx')['default']
  const IIonHelp: typeof import('~icons/ion/help.jsx')['default']
  const IIonHomeOutline: typeof import('~icons/ion/home-outline.jsx')['default']
  const IIonLockClosedOutline: typeof import('~icons/ion/lock-closed-outline.jsx')['default']
  const IIonMailNotificationOutline: typeof import('~icons/ion/mail-notification-outline.jsx')['default']
  const IIonPeopleOutline: typeof import('~icons/ion/people-outline.jsx')['default']
  const IIonPerson: typeof import('~icons/ion/person.jsx')['default']
  const IIonPersonAddOutline: typeof import('~icons/ion/person-add-outline.jsx')['default']
  const IIonPersonOutline: typeof import('~icons/ion/person-outline.jsx')['default']
  const IIonPieChartOutline: typeof import('~icons/ion/pie-chart-outline.jsx')['default']
  const IIonSendOutline: typeof import('~icons/ion/send-outline.jsx')['default']
  const IIonTimerOutline: typeof import('~icons/ion/timer-outline.jsx')['default']
  const IMdiMenu: typeof import('~icons/mdi/menu.jsx')['default']
  const IMdiMenuOpen: typeof import('~icons/mdi/menu-open.jsx')['default']
}
