/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IBxCalendarCheck: typeof import('~icons/bx/calendar-check.jsx')['default']
  const IIonCheckmark: typeof import('~icons/ion/checkmark.jsx')['default']
  const IIonChevronBack: typeof import('~icons/ion/chevron-back.jsx')['default']
  const IIonChevronDown: typeof import('~icons/ion/chevron-down.jsx')['default']
  const IIonChevronForward: typeof import('~icons/ion/chevron-forward.jsx')['default']
  const IIonClock: typeof import('~icons/ion/clock.jsx')['default']
  const IIonClockCircleOutlined: typeof import('~icons/ion/clock-circle-outlined.jsx')['default']
  const IIonList: typeof import('~icons/ion/list.jsx')['default']
  const IIonPause: typeof import('~icons/ion/pause.jsx')['default']
  const IIonPerson: typeof import('~icons/ion/person.jsx')['default']
  const IIonPersonAddOutline: typeof import('~icons/ion/person-add-outline.jsx')['default']
  const IIonPlay: typeof import('~icons/ion/play.jsx')['default']
  const IIonPlayCircleOutlined: typeof import('~icons/ion/play-circle-outlined.jsx')['default']
  const IIonPlus: typeof import('~icons/ion/plus.jsx')['default']
  const IIonRefresh: typeof import('~icons/ion/refresh.jsx')['default']
  const IIonSaveOutline: typeof import('~icons/ion/save-outline.jsx')['default']
  const IIonTrashOutline: typeof import('~icons/ion/trash-outline.jsx')['default']
  const IMdiMenu: typeof import('~icons/mdi/menu.jsx')['default']
  const IMdiMenuOpen: typeof import('~icons/mdi/menu-open.jsx')['default']
}
