/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BioStarSyncHistoricalEventsResponse
 */
export interface BioStarSyncHistoricalEventsResponse {
    /**
     * 
     * @type {number}
     * @memberof BioStarSyncHistoricalEventsResponse
     */
    loadCount: number;
    /**
     * 
     * @type {number}
     * @memberof BioStarSyncHistoricalEventsResponse
     */
    newCount: number;
    /**
     * 
     * @type {number}
     * @memberof BioStarSyncHistoricalEventsResponse
     */
    updateCount: number;
}

/**
 * Check if a given object implements the BioStarSyncHistoricalEventsResponse interface.
 */
export function instanceOfBioStarSyncHistoricalEventsResponse(value: object): value is BioStarSyncHistoricalEventsResponse {
    if (!('loadCount' in value) || value['loadCount'] === undefined) return false;
    if (!('newCount' in value) || value['newCount'] === undefined) return false;
    if (!('updateCount' in value) || value['updateCount'] === undefined) return false;
    return true;
}

export function BioStarSyncHistoricalEventsResponseFromJSON(json: any): BioStarSyncHistoricalEventsResponse {
    return BioStarSyncHistoricalEventsResponseFromJSONTyped(json, false);
}

export function BioStarSyncHistoricalEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BioStarSyncHistoricalEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'loadCount': json['loadCount'],
        'newCount': json['newCount'],
        'updateCount': json['updateCount'],
    };
}

export function BioStarSyncHistoricalEventsResponseToJSON(json: any): BioStarSyncHistoricalEventsResponse {
    return BioStarSyncHistoricalEventsResponseToJSONTyped(json, false);
}

export function BioStarSyncHistoricalEventsResponseToJSONTyped(value?: BioStarSyncHistoricalEventsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'loadCount': value['loadCount'],
        'newCount': value['newCount'],
        'updateCount': value['updateCount'],
    };
}

