/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BioStarSyncAllUsersResponse
 */
export interface BioStarSyncAllUsersResponse {
    /**
     * 
     * @type {number}
     * @memberof BioStarSyncAllUsersResponse
     */
    loadCount: number;
    /**
     * 
     * @type {number}
     * @memberof BioStarSyncAllUsersResponse
     */
    newCount: number;
}

/**
 * Check if a given object implements the BioStarSyncAllUsersResponse interface.
 */
export function instanceOfBioStarSyncAllUsersResponse(value: object): value is BioStarSyncAllUsersResponse {
    if (!('loadCount' in value) || value['loadCount'] === undefined) return false;
    if (!('newCount' in value) || value['newCount'] === undefined) return false;
    return true;
}

export function BioStarSyncAllUsersResponseFromJSON(json: any): BioStarSyncAllUsersResponse {
    return BioStarSyncAllUsersResponseFromJSONTyped(json, false);
}

export function BioStarSyncAllUsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BioStarSyncAllUsersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'loadCount': json['loadCount'],
        'newCount': json['newCount'],
    };
}

export function BioStarSyncAllUsersResponseToJSON(json: any): BioStarSyncAllUsersResponse {
    return BioStarSyncAllUsersResponseToJSONTyped(json, false);
}

export function BioStarSyncAllUsersResponseToJSONTyped(value?: BioStarSyncAllUsersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'loadCount': value['loadCount'],
        'newCount': value['newCount'],
    };
}

