/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BioStarSyncHistoricalEventsResponse {
    'loadCount': number;
    'newCount': number;
    'updateCount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "loadCount",
            "baseName": "loadCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "newCount",
            "baseName": "newCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "updateCount",
            "baseName": "updateCount",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return BioStarSyncHistoricalEventsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
