/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkScheduleCommand
 */
export interface CreateWorkScheduleCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateWorkScheduleCommand
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkScheduleCommand
     */
    startTimeMorning?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkScheduleCommand
     */
    endTimeMorning?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkScheduleCommand
     */
    startTimeAfternoon?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkScheduleCommand
     */
    endTimeAfternoon?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateWorkScheduleCommand
     */
    allowedLateMinutes?: number;
}

/**
 * Check if a given object implements the CreateWorkScheduleCommand interface.
 */
export function instanceOfCreateWorkScheduleCommand(value: object): value is CreateWorkScheduleCommand {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateWorkScheduleCommandFromJSON(json: any): CreateWorkScheduleCommand {
    return CreateWorkScheduleCommandFromJSONTyped(json, false);
}

export function CreateWorkScheduleCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkScheduleCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'startTimeMorning': json['startTimeMorning'] == null ? undefined : json['startTimeMorning'],
        'endTimeMorning': json['endTimeMorning'] == null ? undefined : json['endTimeMorning'],
        'startTimeAfternoon': json['startTimeAfternoon'] == null ? undefined : json['startTimeAfternoon'],
        'endTimeAfternoon': json['endTimeAfternoon'] == null ? undefined : json['endTimeAfternoon'],
        'allowedLateMinutes': json['allowedLateMinutes'] == null ? undefined : json['allowedLateMinutes'],
    };
}

export function CreateWorkScheduleCommandToJSON(json: any): CreateWorkScheduleCommand {
    return CreateWorkScheduleCommandToJSONTyped(json, false);
}

export function CreateWorkScheduleCommandToJSONTyped(value?: CreateWorkScheduleCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'startTimeMorning': value['startTimeMorning'],
        'endTimeMorning': value['endTimeMorning'],
        'startTimeAfternoon': value['startTimeAfternoon'],
        'endTimeAfternoon': value['endTimeAfternoon'],
        'allowedLateMinutes': value['allowedLateMinutes'],
    };
}

