/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestType } from './RequestType';
import {
    RequestTypeFromJSON,
    RequestTypeFromJSONTyped,
    RequestTypeToJSON,
    RequestTypeToJSONTyped,
} from './RequestType';

/**
 * 
 * @export
 * @interface CreateLeaveRequestDto
 */
export interface CreateLeaveRequestDto {
    /**
     * 
     * @type {Date}
     * @memberof CreateLeaveRequestDto
     */
    date: Date;
    /**
     * 
     * @type {RequestType}
     * @memberof CreateLeaveRequestDto
     */
    requestType: RequestType;
    /**
     * 
     * @type {string}
     * @memberof CreateLeaveRequestDto
     */
    reason: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLeaveRequestDto
     */
    approverId?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateLeaveRequestDto
     */
    breakStartDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateLeaveRequestDto
     */
    breakEndDate: Date;
}



/**
 * Check if a given object implements the CreateLeaveRequestDto interface.
 */
export function instanceOfCreateLeaveRequestDto(value: object): value is CreateLeaveRequestDto {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('requestType' in value) || value['requestType'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('breakStartDate' in value) || value['breakStartDate'] === undefined) return false;
    if (!('breakEndDate' in value) || value['breakEndDate'] === undefined) return false;
    return true;
}

export function CreateLeaveRequestDtoFromJSON(json: any): CreateLeaveRequestDto {
    return CreateLeaveRequestDtoFromJSONTyped(json, false);
}

export function CreateLeaveRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLeaveRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'requestType': RequestTypeFromJSON(json['requestType']),
        'reason': json['reason'],
        'approverId': json['approverId'] == null ? undefined : json['approverId'],
        'breakStartDate': (new Date(json['breakStartDate'])),
        'breakEndDate': (new Date(json['breakEndDate'])),
    };
}

export function CreateLeaveRequestDtoToJSON(json: any): CreateLeaveRequestDto {
    return CreateLeaveRequestDtoToJSONTyped(json, false);
}

export function CreateLeaveRequestDtoToJSONTyped(value?: CreateLeaveRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': ((value['date']).toISOString()),
        'requestType': RequestTypeToJSON(value['requestType']),
        'reason': value['reason'],
        'approverId': value['approverId'],
        'breakStartDate': ((value['breakStartDate']).toISOString()),
        'breakEndDate': ((value['breakEndDate']).toISOString()),
    };
}

