/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CursorPagedRequestDirection = {
    Next: 'Next',
    Previous: 'Previous'
} as const;
export type CursorPagedRequestDirection = typeof CursorPagedRequestDirection[keyof typeof CursorPagedRequestDirection];


export function instanceOfCursorPagedRequestDirection(value: any): boolean {
    for (const key in CursorPagedRequestDirection) {
        if (Object.prototype.hasOwnProperty.call(CursorPagedRequestDirection, key)) {
            if (CursorPagedRequestDirection[key as keyof typeof CursorPagedRequestDirection] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CursorPagedRequestDirectionFromJSON(json: any): CursorPagedRequestDirection {
    return CursorPagedRequestDirectionFromJSONTyped(json, false);
}

export function CursorPagedRequestDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorPagedRequestDirection {
    return json as CursorPagedRequestDirection;
}

export function CursorPagedRequestDirectionToJSON(value?: CursorPagedRequestDirection | null): any {
    return value as any;
}

export function CursorPagedRequestDirectionToJSONTyped(value: any, ignoreDiscriminator: boolean): CursorPagedRequestDirection {
    return value as CursorPagedRequestDirection;
}

