/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceReferenceDto } from './DeviceReferenceDto';
import {
    DeviceReferenceDtoFromJSON,
    DeviceReferenceDtoFromJSONTyped,
    DeviceReferenceDtoToJSON,
    DeviceReferenceDtoToJSONTyped,
} from './DeviceReferenceDto';

/**
 * 
 * @export
 * @interface DeviceCategoryDetailsDto
 */
export interface DeviceCategoryDetailsDto {
    /**
     * 
     * @type {number}
     * @memberof DeviceCategoryDetailsDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof DeviceCategoryDetailsDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceCategoryDetailsDto
     */
    description?: string | null;
    /**
     * 
     * @type {Array<DeviceReferenceDto>}
     * @memberof DeviceCategoryDetailsDto
     */
    devices?: Array<DeviceReferenceDto> | null;
}

/**
 * Check if a given object implements the DeviceCategoryDetailsDto interface.
 */
export function instanceOfDeviceCategoryDetailsDto(value: object): value is DeviceCategoryDetailsDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DeviceCategoryDetailsDtoFromJSON(json: any): DeviceCategoryDetailsDto {
    return DeviceCategoryDetailsDtoFromJSONTyped(json, false);
}

export function DeviceCategoryDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceCategoryDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'devices': json['devices'] == null ? undefined : ((json['devices'] as Array<any>).map(DeviceReferenceDtoFromJSON)),
    };
}

export function DeviceCategoryDetailsDtoToJSON(json: any): DeviceCategoryDetailsDto {
    return DeviceCategoryDetailsDtoToJSONTyped(json, false);
}

export function DeviceCategoryDetailsDtoToJSONTyped(value?: DeviceCategoryDetailsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'devices': value['devices'] == null ? undefined : ((value['devices'] as Array<any>).map(DeviceReferenceDtoToJSON)),
    };
}

