/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserReferenceDto } from './UserReferenceDto';
import {
    UserReferenceDtoFromJSON,
    UserReferenceDtoFromJSONTyped,
    UserReferenceDtoToJSON,
    UserReferenceDtoToJSONTyped,
} from './UserReferenceDto';
import type { DeviceCategoryReferenceDto } from './DeviceCategoryReferenceDto';
import {
    DeviceCategoryReferenceDtoFromJSON,
    DeviceCategoryReferenceDtoFromJSONTyped,
    DeviceCategoryReferenceDtoToJSON,
    DeviceCategoryReferenceDtoToJSONTyped,
} from './DeviceCategoryReferenceDto';
import type { DeviceStatus } from './DeviceStatus';
import {
    DeviceStatusFromJSON,
    DeviceStatusFromJSONTyped,
    DeviceStatusToJSON,
    DeviceStatusToJSONTyped,
} from './DeviceStatus';

/**
 * 
 * @export
 * @interface DeviceDetailsDto
 */
export interface DeviceDetailsDto {
    /**
     * 
     * @type {number}
     * @memberof DeviceDetailsDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof DeviceDetailsDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceDetailsDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceDetailsDto
     */
    location?: string | null;
    /**
     * 
     * @type {DeviceStatus}
     * @memberof DeviceDetailsDto
     */
    status?: DeviceStatus;
    /**
     * 
     * @type {UserReferenceDto}
     * @memberof DeviceDetailsDto
     */
    assignedUser?: UserReferenceDto;
    /**
     * 
     * @type {Array<DeviceCategoryReferenceDto>}
     * @memberof DeviceDetailsDto
     */
    deviceCategories?: Array<DeviceCategoryReferenceDto> | null;
}



/**
 * Check if a given object implements the DeviceDetailsDto interface.
 */
export function instanceOfDeviceDetailsDto(value: object): value is DeviceDetailsDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DeviceDetailsDtoFromJSON(json: any): DeviceDetailsDto {
    return DeviceDetailsDtoFromJSONTyped(json, false);
}

export function DeviceDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : json['location'],
        'status': json['status'] == null ? undefined : DeviceStatusFromJSON(json['status']),
        'assignedUser': json['assignedUser'] == null ? undefined : UserReferenceDtoFromJSON(json['assignedUser']),
        'deviceCategories': json['deviceCategories'] == null ? undefined : ((json['deviceCategories'] as Array<any>).map(DeviceCategoryReferenceDtoFromJSON)),
    };
}

export function DeviceDetailsDtoToJSON(json: any): DeviceDetailsDto {
    return DeviceDetailsDtoToJSONTyped(json, false);
}

export function DeviceDetailsDtoToJSONTyped(value?: DeviceDetailsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'location': value['location'],
        'status': DeviceStatusToJSON(value['status']),
        'assignedUser': UserReferenceDtoToJSON(value['assignedUser']),
        'deviceCategories': value['deviceCategories'] == null ? undefined : ((value['deviceCategories'] as Array<any>).map(DeviceCategoryReferenceDtoToJSON)),
    };
}

