/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationCategory } from './NotificationCategory';
import {
    NotificationCategoryFromJSON,
    NotificationCategoryFromJSONTyped,
    NotificationCategoryToJSON,
    NotificationCategoryToJSONTyped,
} from './NotificationCategory';

/**
 * 
 * @export
 * @interface NotificationDetailsDto
 */
export interface NotificationDetailsDto {
    /**
     * 
     * @type {number}
     * @memberof NotificationDetailsDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof NotificationDetailsDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDetailsDto
     */
    message: string;
    /**
     * 
     * @type {NotificationCategory}
     * @memberof NotificationDetailsDto
     */
    category: NotificationCategory;
    /**
     * 
     * @type {string}
     * @memberof NotificationDetailsDto
     */
    relatedEntityId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof NotificationDetailsDto
     */
    date: Date;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationDetailsDto
     */
    isRead: boolean;
}



/**
 * Check if a given object implements the NotificationDetailsDto interface.
 */
export function instanceOfNotificationDetailsDto(value: object): value is NotificationDetailsDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    return true;
}

export function NotificationDetailsDtoFromJSON(json: any): NotificationDetailsDto {
    return NotificationDetailsDtoFromJSONTyped(json, false);
}

export function NotificationDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'message': json['message'],
        'category': NotificationCategoryFromJSON(json['category']),
        'relatedEntityId': json['relatedEntityId'] == null ? undefined : json['relatedEntityId'],
        'date': (new Date(json['date'])),
        'isRead': json['isRead'],
    };
}

export function NotificationDetailsDtoToJSON(json: any): NotificationDetailsDto {
    return NotificationDetailsDtoToJSONTyped(json, false);
}

export function NotificationDetailsDtoToJSONTyped(value?: NotificationDetailsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'message': value['message'],
        'category': NotificationCategoryToJSON(value['category']),
        'relatedEntityId': value['relatedEntityId'],
        'date': ((value['date']).toISOString()),
        'isRead': value['isRead'],
    };
}

