/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationDto } from './NotificationDto';
import {
    NotificationDtoFromJSON,
    NotificationDtoFromJSONTyped,
    NotificationDtoToJSON,
    NotificationDtoToJSONTyped,
} from './NotificationDto';

/**
 * 
 * @export
 * @interface NotificationDtoCursorPaginated
 */
export interface NotificationDtoCursorPaginated {
    /**
     * 
     * @type {Array<NotificationDto>}
     * @memberof NotificationDtoCursorPaginated
     */
    data: Array<NotificationDto>;
    /**
     * 
     * @type {number}
     * @memberof NotificationDtoCursorPaginated
     */
    lastId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NotificationDtoCursorPaginated
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof NotificationDtoCursorPaginated
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationDtoCursorPaginated
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the NotificationDtoCursorPaginated interface.
 */
export function instanceOfNotificationDtoCursorPaginated(value: object): value is NotificationDtoCursorPaginated {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function NotificationDtoCursorPaginatedFromJSON(json: any): NotificationDtoCursorPaginated {
    return NotificationDtoCursorPaginatedFromJSONTyped(json, false);
}

export function NotificationDtoCursorPaginatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDtoCursorPaginated {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(NotificationDtoFromJSON)),
        'lastId': json['lastId'] == null ? undefined : json['lastId'],
        'limit': json['limit'],
        'totalCount': json['totalCount'],
        'hasMore': json['hasMore'],
    };
}

export function NotificationDtoCursorPaginatedToJSON(json: any): NotificationDtoCursorPaginated {
    return NotificationDtoCursorPaginatedToJSONTyped(json, false);
}

export function NotificationDtoCursorPaginatedToJSONTyped(value?: NotificationDtoCursorPaginated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(NotificationDtoToJSON)),
        'lastId': value['lastId'],
        'limit': value['limit'],
        'totalCount': value['totalCount'],
        'hasMore': value['hasMore'],
    };
}

