/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationDetailsDto } from './NotificationDetailsDto';
import {
    NotificationDetailsDtoFromJSON,
    NotificationDetailsDtoFromJSONTyped,
    NotificationDetailsDtoToJSON,
    NotificationDetailsDtoToJSONTyped,
} from './NotificationDetailsDto';

/**
 * 
 * @export
 * @interface NotificationDetailsDtoCursorPaginated
 */
export interface NotificationDetailsDtoCursorPaginated {
    /**
     * 
     * @type {Array<NotificationDetailsDto>}
     * @memberof NotificationDetailsDtoCursorPaginated
     */
    data: Array<NotificationDetailsDto>;
    /**
     * 
     * @type {number}
     * @memberof NotificationDetailsDtoCursorPaginated
     */
    lastId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NotificationDetailsDtoCursorPaginated
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof NotificationDetailsDtoCursorPaginated
     */
    totalCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationDetailsDtoCursorPaginated
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the NotificationDetailsDtoCursorPaginated interface.
 */
export function instanceOfNotificationDetailsDtoCursorPaginated(value: object): value is NotificationDetailsDtoCursorPaginated {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function NotificationDetailsDtoCursorPaginatedFromJSON(json: any): NotificationDetailsDtoCursorPaginated {
    return NotificationDetailsDtoCursorPaginatedFromJSONTyped(json, false);
}

export function NotificationDetailsDtoCursorPaginatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDetailsDtoCursorPaginated {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(NotificationDetailsDtoFromJSON)),
        'lastId': json['lastId'] == null ? undefined : json['lastId'],
        'limit': json['limit'],
        'totalCount': json['totalCount'],
        'hasMore': json['hasMore'],
    };
}

export function NotificationDetailsDtoCursorPaginatedToJSON(json: any): NotificationDetailsDtoCursorPaginated {
    return NotificationDetailsDtoCursorPaginatedToJSONTyped(json, false);
}

export function NotificationDetailsDtoCursorPaginatedToJSONTyped(value?: NotificationDetailsDtoCursorPaginated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(NotificationDetailsDtoToJSON)),
        'lastId': value['lastId'],
        'limit': value['limit'],
        'totalCount': value['totalCount'],
        'hasMore': value['hasMore'],
    };
}

