/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchCondition } from './SearchCondition';
import {
    SearchConditionFromJSON,
    SearchConditionFromJSONTyped,
    SearchConditionToJSON,
    SearchConditionToJSONTyped,
} from './SearchCondition';

/**
 * 
 * @export
 * @interface PagedRequest
 */
export interface PagedRequest {
    /**
     * 
     * @type {number}
     * @memberof PagedRequest
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PagedRequest
     */
    pageSize: number;
    /**
     * 
     * @type {Array<SearchCondition>}
     * @memberof PagedRequest
     */
    searchConditions?: Array<SearchCondition> | null;
    /**
     * of the form fieldname [ascending|descending],fieldname [ascending|descending]...
     * @type {string}
     * @memberof PagedRequest
     */
    orderBy?: string | null;
}

/**
 * Check if a given object implements the PagedRequest interface.
 */
export function instanceOfPagedRequest(value: object): value is PagedRequest {
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    return true;
}

export function PagedRequestFromJSON(json: any): PagedRequest {
    return PagedRequestFromJSONTyped(json, false);
}

export function PagedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNumber': json['pageNumber'],
        'pageSize': json['pageSize'],
        'searchConditions': json['searchConditions'] == null ? undefined : ((json['searchConditions'] as Array<any>).map(SearchConditionFromJSON)),
        'orderBy': json['orderBy'] == null ? undefined : json['orderBy'],
    };
}

export function PagedRequestToJSON(json: any): PagedRequest {
    return PagedRequestToJSONTyped(json, false);
}

export function PagedRequestToJSONTyped(value?: PagedRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'searchConditions': value['searchConditions'] == null ? undefined : ((value['searchConditions'] as Array<any>).map(SearchConditionToJSON)),
        'orderBy': value['orderBy'],
    };
}

