/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum Permission {
    PermissionsUsersView = 'Permissions.Users.View',
    PermissionsUsersSync = 'Permissions.Users.Sync',
    PermissionsUsersCreate = 'Permissions.Users.Create',
    PermissionsUsersEdit = 'Permissions.Users.Edit',
    PermissionsUsersDelete = 'Permissions.Users.Delete',
    PermissionsUsersExport = 'Permissions.Users.Export',
    PermissionsUsersImport = 'Permissions.Users.Import',
    PermissionsRolesView = 'Permissions.Roles.View',
    PermissionsRolesCreate = 'Permissions.Roles.Create',
    PermissionsRolesEdit = 'Permissions.Roles.Edit',
    PermissionsRolesDelete = 'Permissions.Roles.Delete',
    PermissionsTeamsView = 'Permissions.Teams.View',
    PermissionsTeamsCreate = 'Permissions.Teams.Create',
    PermissionsTeamsEdit = 'Permissions.Teams.Edit',
    PermissionsTeamsDelete = 'Permissions.Teams.Delete',
    PermissionsWorkTimesView = 'Permissions.WorkTimes.View',
    PermissionsWorkTimesCreate = 'Permissions.WorkTimes.Create',
    PermissionsWorkTimesEdit = 'Permissions.WorkTimes.Edit',
    PermissionsWorkTimesDelete = 'Permissions.WorkTimes.Delete',
    PermissionsProjectsView = 'Permissions.Projects.View',
    PermissionsProjectsCreate = 'Permissions.Projects.Create',
    PermissionsProjectsEdit = 'Permissions.Projects.Edit',
    PermissionsProjectsDelete = 'Permissions.Projects.Delete',
    PermissionsDevicesView = 'Permissions.Devices.View',
    PermissionsDevicesCreate = 'Permissions.Devices.Create',
    PermissionsDevicesEdit = 'Permissions.Devices.Edit',
    PermissionsDevicesDelete = 'Permissions.Devices.Delete',
    PermissionsTimesheetsView = 'Permissions.Timesheets.View',
    PermissionsTimesheetsExport = 'Permissions.Timesheets.Export',
    PermissionsSystemSendEmail = 'Permissions.System.SendEmail',
    PermissionsSystemReport = 'Permissions.System.Report'
}
