/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Permission = {
    PermissionsUsersView: 'Permissions.Users.View',
    PermissionsUsersCreate: 'Permissions.Users.Create',
    PermissionsUsersEdit: 'Permissions.Users.Edit',
    PermissionsUsersDelete: 'Permissions.Users.Delete',
    PermissionsUsersExport: 'Permissions.Users.Export',
    PermissionsUsersImport: 'Permissions.Users.Import',
    PermissionsRolesView: 'Permissions.Roles.View',
    PermissionsRolesCreate: 'Permissions.Roles.Create',
    PermissionsRolesEdit: 'Permissions.Roles.Edit',
    PermissionsRolesDelete: 'Permissions.Roles.Delete',
    PermissionsTeamsView: 'Permissions.Teams.View',
    PermissionsTeamsCreate: 'Permissions.Teams.Create',
    PermissionsTeamsEdit: 'Permissions.Teams.Edit',
    PermissionsTeamsDelete: 'Permissions.Teams.Delete',
    PermissionsWorkTimesView: 'Permissions.WorkTimes.View',
    PermissionsWorkTimesCreate: 'Permissions.WorkTimes.Create',
    PermissionsWorkTimesEdit: 'Permissions.WorkTimes.Edit',
    PermissionsWorkTimesDelete: 'Permissions.WorkTimes.Delete',
    PermissionsProjectsView: 'Permissions.Projects.View',
    PermissionsProjectsCreate: 'Permissions.Projects.Create',
    PermissionsProjectsEdit: 'Permissions.Projects.Edit',
    PermissionsProjectsDelete: 'Permissions.Projects.Delete',
    PermissionsDevicesView: 'Permissions.Devices.View',
    PermissionsDevicesCreate: 'Permissions.Devices.Create',
    PermissionsDevicesEdit: 'Permissions.Devices.Edit',
    PermissionsDevicesDelete: 'Permissions.Devices.Delete',
    PermissionsTimesheetsView: 'Permissions.Timesheets.View',
    PermissionsTimesheetsExport: 'Permissions.Timesheets.Export',
    PermissionsSystemSendEmail: 'Permissions.System.SendEmail',
    PermissionsSystemReport: 'Permissions.System.Report',
    PermissionsBioStarSyncUsers: 'Permissions.BioStar.SyncUsers',
    PermissionsBioStarSyncTimesheets: 'Permissions.BioStar.SyncTimesheets'
} as const;
export type Permission = typeof Permission[keyof typeof Permission];


export function instanceOfPermission(value: any): boolean {
    for (const key in Permission) {
        if (Object.prototype.hasOwnProperty.call(Permission, key)) {
            if (Permission[key as keyof typeof Permission] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PermissionFromJSON(json: any): Permission {
    return PermissionFromJSONTyped(json, false);
}

export function PermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Permission {
    return json as Permission;
}

export function PermissionToJSON(value?: Permission | null): any {
    return value as any;
}

export function PermissionToJSONTyped(value: any, ignoreDiscriminator: boolean): Permission {
    return value as Permission;
}

