/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectStatus } from './ProjectStatus';
import {
    ProjectStatusFromJSON,
    ProjectStatusFromJSONTyped,
    ProjectStatusToJSON,
    ProjectStatusToJSONTyped,
} from './ProjectStatus';
import type { TeamMinimalDto } from './TeamMinimalDto';
import {
    TeamMinimalDtoFromJSON,
    TeamMinimalDtoFromJSONTyped,
    TeamMinimalDtoToJSON,
    TeamMinimalDtoToJSONTyped,
} from './TeamMinimalDto';
import type { UserMinimalDto } from './UserMinimalDto';
import {
    UserMinimalDtoFromJSON,
    UserMinimalDtoFromJSONTyped,
    UserMinimalDtoToJSON,
    UserMinimalDtoToJSONTyped,
} from './UserMinimalDto';

/**
 * 
 * @export
 * @interface ProjectDto
 */
export interface ProjectDto {
    /**
     * 
     * @type {number}
     * @memberof ProjectDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDto
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectDto
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectDto
     */
    endDate?: Date | null;
    /**
     * 
     * @type {ProjectStatus}
     * @memberof ProjectDto
     */
    status: ProjectStatus;
    /**
     * 
     * @type {TeamMinimalDto}
     * @memberof ProjectDto
     */
    team?: TeamMinimalDto;
    /**
     * 
     * @type {UserMinimalDto}
     * @memberof ProjectDto
     */
    manager?: UserMinimalDto;
    /**
     * 
     * @type {Array<UserMinimalDto>}
     * @memberof ProjectDto
     */
    members?: Array<UserMinimalDto> | null;
}



/**
 * Check if a given object implements the ProjectDto interface.
 */
export function instanceOfProjectDto(value: object): value is ProjectDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ProjectDtoFromJSON(json: any): ProjectDto {
    return ProjectDtoFromJSONTyped(json, false);
}

export function ProjectDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'status': ProjectStatusFromJSON(json['status']),
        'team': json['team'] == null ? undefined : TeamMinimalDtoFromJSON(json['team']),
        'manager': json['manager'] == null ? undefined : UserMinimalDtoFromJSON(json['manager']),
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(UserMinimalDtoFromJSON)),
    };
}

export function ProjectDtoToJSON(json: any): ProjectDto {
    return ProjectDtoToJSONTyped(json, false);
}

export function ProjectDtoToJSONTyped(value?: ProjectDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
        'status': ProjectStatusToJSON(value['status']),
        'team': TeamMinimalDtoToJSON(value['team']),
        'manager': UserMinimalDtoToJSON(value['manager']),
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(UserMinimalDtoToJSON)),
    };
}

