/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectDto } from './ProjectDto';
import {
    ProjectDtoFromJSON,
    ProjectDtoFromJSONTyped,
    ProjectDtoToJSON,
    ProjectDtoToJSONTyped,
} from './ProjectDto';

/**
 * 
 * @export
 * @interface ProjectDtoPaginated
 */
export interface ProjectDtoPaginated {
    /**
     * 
     * @type {Array<ProjectDto>}
     * @memberof ProjectDtoPaginated
     */
    data: Array<ProjectDto>;
    /**
     * 
     * @type {number}
     * @memberof ProjectDtoPaginated
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectDtoPaginated
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectDtoPaginated
     */
    totalCount: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectDtoPaginated
     */
    pageSize: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectDtoPaginated
     */
    readonly hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectDtoPaginated
     */
    readonly hasNextPage: boolean;
}

/**
 * Check if a given object implements the ProjectDtoPaginated interface.
 */
export function instanceOfProjectDtoPaginated(value: object): value is ProjectDtoPaginated {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    return true;
}

export function ProjectDtoPaginatedFromJSON(json: any): ProjectDtoPaginated {
    return ProjectDtoPaginatedFromJSONTyped(json, false);
}

export function ProjectDtoPaginatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDtoPaginated {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ProjectDtoFromJSON)),
        'currentPage': json['currentPage'],
        'totalPages': json['totalPages'],
        'totalCount': json['totalCount'],
        'pageSize': json['pageSize'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function ProjectDtoPaginatedToJSON(json: any): ProjectDtoPaginated {
    return ProjectDtoPaginatedToJSONTyped(json, false);
}

export function ProjectDtoPaginatedToJSONTyped(value?: Omit<ProjectDtoPaginated, 'hasPreviousPage'|'hasNextPage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ProjectDtoToJSON)),
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'pageSize': value['pageSize'],
    };
}

