/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectDetailsDto } from './ProjectDetailsDto';
import {
    ProjectDetailsDtoFromJSON,
    ProjectDetailsDtoFromJSONTyped,
    ProjectDetailsDtoToJSON,
    ProjectDetailsDtoToJSONTyped,
} from './ProjectDetailsDto';

/**
 * 
 * @export
 * @interface ProjectDetailsDtoPaginated
 */
export interface ProjectDetailsDtoPaginated {
    /**
     * 
     * @type {Array<ProjectDetailsDto>}
     * @memberof ProjectDetailsDtoPaginated
     */
    data: Array<ProjectDetailsDto>;
    /**
     * 
     * @type {number}
     * @memberof ProjectDetailsDtoPaginated
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectDetailsDtoPaginated
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectDetailsDtoPaginated
     */
    totalCount: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectDetailsDtoPaginated
     */
    pageSize: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectDetailsDtoPaginated
     */
    readonly hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectDetailsDtoPaginated
     */
    readonly hasNextPage: boolean;
}

/**
 * Check if a given object implements the ProjectDetailsDtoPaginated interface.
 */
export function instanceOfProjectDetailsDtoPaginated(value: object): value is ProjectDetailsDtoPaginated {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    return true;
}

export function ProjectDetailsDtoPaginatedFromJSON(json: any): ProjectDetailsDtoPaginated {
    return ProjectDetailsDtoPaginatedFromJSONTyped(json, false);
}

export function ProjectDetailsDtoPaginatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDetailsDtoPaginated {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ProjectDetailsDtoFromJSON)),
        'currentPage': json['currentPage'],
        'totalPages': json['totalPages'],
        'totalCount': json['totalCount'],
        'pageSize': json['pageSize'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function ProjectDetailsDtoPaginatedToJSON(json: any): ProjectDetailsDtoPaginated {
    return ProjectDetailsDtoPaginatedToJSONTyped(json, false);
}

export function ProjectDetailsDtoPaginatedToJSONTyped(value?: Omit<ProjectDetailsDtoPaginated, 'hasPreviousPage'|'hasNextPage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ProjectDetailsDtoToJSON)),
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'pageSize': value['pageSize'],
    };
}

