/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestStatus } from './RequestStatus';
import {
    RequestStatusFromJSON,
    RequestStatusFromJSONTyped,
    RequestStatusToJSON,
    RequestStatusToJSONTyped,
} from './RequestStatus';
import type { RequestType } from './RequestType';
import {
    RequestTypeFromJSON,
    RequestTypeFromJSONTyped,
    RequestTypeToJSON,
    RequestTypeToJSONTyped,
} from './RequestType';

/**
 * 
 * @export
 * @interface RequestCombinedReferenceDto
 */
export interface RequestCombinedReferenceDto {
    /**
     * 
     * @type {number}
     * @memberof RequestCombinedReferenceDto
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof RequestCombinedReferenceDto
     */
    date: Date;
    /**
     * 
     * @type {RequestType}
     * @memberof RequestCombinedReferenceDto
     */
    requestType: RequestType;
    /**
     * 
     * @type {string}
     * @memberof RequestCombinedReferenceDto
     */
    reason: string;
    /**
     * 
     * @type {RequestStatus}
     * @memberof RequestCombinedReferenceDto
     */
    status: RequestStatus;
    /**
     * 
     * @type {Date}
     * @memberof RequestCombinedReferenceDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof RequestCombinedReferenceDto
     */
    breakStartDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof RequestCombinedReferenceDto
     */
    breakEndDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof RequestCombinedReferenceDto
     */
    checkIn: Date;
    /**
     * 
     * @type {Date}
     * @memberof RequestCombinedReferenceDto
     */
    checkOut: Date;
}



/**
 * Check if a given object implements the RequestCombinedReferenceDto interface.
 */
export function instanceOfRequestCombinedReferenceDto(value: object): value is RequestCombinedReferenceDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('requestType' in value) || value['requestType'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('breakStartDate' in value) || value['breakStartDate'] === undefined) return false;
    if (!('breakEndDate' in value) || value['breakEndDate'] === undefined) return false;
    if (!('checkIn' in value) || value['checkIn'] === undefined) return false;
    if (!('checkOut' in value) || value['checkOut'] === undefined) return false;
    return true;
}

export function RequestCombinedReferenceDtoFromJSON(json: any): RequestCombinedReferenceDto {
    return RequestCombinedReferenceDtoFromJSONTyped(json, false);
}

export function RequestCombinedReferenceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestCombinedReferenceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': (new Date(json['date'])),
        'requestType': RequestTypeFromJSON(json['requestType']),
        'reason': json['reason'],
        'status': RequestStatusFromJSON(json['status']),
        'createdAt': (new Date(json['createdAt'])),
        'breakStartDate': (new Date(json['breakStartDate'])),
        'breakEndDate': (new Date(json['breakEndDate'])),
        'checkIn': (new Date(json['checkIn'])),
        'checkOut': (new Date(json['checkOut'])),
    };
}

export function RequestCombinedReferenceDtoToJSON(json: any): RequestCombinedReferenceDto {
    return RequestCombinedReferenceDtoToJSONTyped(json, false);
}

export function RequestCombinedReferenceDtoToJSONTyped(value?: RequestCombinedReferenceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date': ((value['date']).toISOString()),
        'requestType': RequestTypeToJSON(value['requestType']),
        'reason': value['reason'],
        'status': RequestStatusToJSON(value['status']),
        'createdAt': ((value['createdAt']).toISOString()),
        'breakStartDate': ((value['breakStartDate']).toISOString()),
        'breakEndDate': ((value['breakEndDate']).toISOString()),
        'checkIn': ((value['checkIn']).toISOString()),
        'checkOut': ((value['checkOut']).toISOString()),
    };
}

