/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RequestType = {
    TimesheetAdjustmentRequest: 'TIMESHEET_ADJUSTMENT_REQUEST',
    LeaveRequest: 'LEAVE_REQUEST',
    CancelRequest: 'CANCEL_REQUEST',
    OvertimeRequest: 'OVERTIME_REQUEST',
    WorkFromHomeRequest: 'WORK_FROM_HOME_REQUEST'
} as const;
export type RequestType = typeof RequestType[keyof typeof RequestType];


export function instanceOfRequestType(value: any): boolean {
    for (const key in RequestType) {
        if (Object.prototype.hasOwnProperty.call(RequestType, key)) {
            if (RequestType[key as keyof typeof RequestType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RequestTypeFromJSON(json: any): RequestType {
    return RequestTypeFromJSONTyped(json, false);
}

export function RequestTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestType {
    return json as RequestType;
}

export function RequestTypeToJSON(value?: RequestType | null): any {
    return value as any;
}

export function RequestTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): RequestType {
    return value as RequestType;
}

