/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleFormDto
 */
export interface RoleFormDto {
    /**
     * 
     * @type {string}
     * @memberof RoleFormDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RoleFormDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RoleFormDto
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof RoleFormDto
     */
    isAdmin: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof RoleFormDto
     */
    permissions: Array<string>;
}

/**
 * Check if a given object implements the RoleFormDto interface.
 */
export function instanceOfRoleFormDto(value: object): value is RoleFormDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('isAdmin' in value) || value['isAdmin'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function RoleFormDtoFromJSON(json: any): RoleFormDto {
    return RoleFormDtoFromJSONTyped(json, false);
}

export function RoleFormDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleFormDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'isAdmin': json['isAdmin'],
        'permissions': json['permissions'],
    };
}

export function RoleFormDtoToJSON(json: any): RoleFormDto {
    return RoleFormDtoToJSONTyped(json, false);
}

export function RoleFormDtoToJSONTyped(value?: RoleFormDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'isAdmin': value['isAdmin'],
        'permissions': value['permissions'],
    };
}

