/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleCreateUpdateRequest
 */
export interface RoleCreateUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof RoleCreateUpdateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RoleCreateUpdateRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof RoleCreateUpdateRequest
     */
    permissions?: Array<string> | null;
}

/**
 * Check if a given object implements the RoleCreateUpdateRequest interface.
 */
export function instanceOfRoleCreateUpdateRequest(value: object): value is RoleCreateUpdateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RoleCreateUpdateRequestFromJSON(json: any): RoleCreateUpdateRequest {
    return RoleCreateUpdateRequestFromJSONTyped(json, false);
}

export function RoleCreateUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleCreateUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'permissions': json['permissions'] == null ? undefined : json['permissions'],
    };
}

export function RoleCreateUpdateRequestToJSON(json: any): RoleCreateUpdateRequest {
    return RoleCreateUpdateRequestToJSONTyped(json, false);
}

export function RoleCreateUpdateRequestToJSONTyped(value?: RoleCreateUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'permissions': value['permissions'],
    };
}

