/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleDetailsDto
 */
export interface RoleDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof RoleDetailsDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RoleDetailsDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RoleDetailsDto
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof RoleDetailsDto
     */
    isAdmin: boolean;
}

/**
 * Check if a given object implements the RoleDetailsDto interface.
 */
export function instanceOfRoleDetailsDto(value: object): value is RoleDetailsDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('isAdmin' in value) || value['isAdmin'] === undefined) return false;
    return true;
}

export function RoleDetailsDtoFromJSON(json: any): RoleDetailsDto {
    return RoleDetailsDtoFromJSONTyped(json, false);
}

export function RoleDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'isAdmin': json['isAdmin'],
    };
}

export function RoleDetailsDtoToJSON(json: any): RoleDetailsDto {
    return RoleDetailsDtoToJSONTyped(json, false);
}

export function RoleDetailsDtoToJSONTyped(value?: RoleDetailsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'isAdmin': value['isAdmin'],
    };
}

