/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemNotificationMessageSeverity } from './SystemNotificationMessageSeverity';
import {
    SystemNotificationMessageSeverityFromJSON,
    SystemNotificationMessageSeverityFromJSONTyped,
    SystemNotificationMessageSeverityToJSON,
    SystemNotificationMessageSeverityToJSONTyped,
} from './SystemNotificationMessageSeverity';

/**
 * 
 * @export
 * @interface SystemNotificationMessageDto
 */
export interface SystemNotificationMessageDto {
    /**
     * 
     * @type {string}
     * @memberof SystemNotificationMessageDto
     */
    title: string | null;
    /**
     * 
     * @type {string}
     * @memberof SystemNotificationMessageDto
     */
    body: string | null;
    /**
     * 
     * @type {SystemNotificationMessageSeverity}
     * @memberof SystemNotificationMessageDto
     */
    severity?: SystemNotificationMessageSeverity;
}



/**
 * Check if a given object implements the SystemNotificationMessageDto interface.
 */
export function instanceOfSystemNotificationMessageDto(value: object): value is SystemNotificationMessageDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function SystemNotificationMessageDtoFromJSON(json: any): SystemNotificationMessageDto {
    return SystemNotificationMessageDtoFromJSONTyped(json, false);
}

export function SystemNotificationMessageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemNotificationMessageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'body': json['body'],
        'severity': json['severity'] == null ? undefined : SystemNotificationMessageSeverityFromJSON(json['severity']),
    };
}

export function SystemNotificationMessageDtoToJSON(json: any): SystemNotificationMessageDto {
    return SystemNotificationMessageDtoToJSONTyped(json, false);
}

export function SystemNotificationMessageDtoToJSONTyped(value?: SystemNotificationMessageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'body': value['body'],
        'severity': SystemNotificationMessageSeverityToJSON(value['severity']),
    };
}

