/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SystemNotificationMessageSeverity = {
    Info: 'Info',
    Warning: 'Warning',
    Error: 'Error'
} as const;
export type SystemNotificationMessageSeverity = typeof SystemNotificationMessageSeverity[keyof typeof SystemNotificationMessageSeverity];


export function instanceOfSystemNotificationMessageSeverity(value: any): boolean {
    for (const key in SystemNotificationMessageSeverity) {
        if (Object.prototype.hasOwnProperty.call(SystemNotificationMessageSeverity, key)) {
            if (SystemNotificationMessageSeverity[key as keyof typeof SystemNotificationMessageSeverity] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SystemNotificationMessageSeverityFromJSON(json: any): SystemNotificationMessageSeverity {
    return SystemNotificationMessageSeverityFromJSONTyped(json, false);
}

export function SystemNotificationMessageSeverityFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemNotificationMessageSeverity {
    return json as SystemNotificationMessageSeverity;
}

export function SystemNotificationMessageSeverityToJSON(value?: SystemNotificationMessageSeverity | null): any {
    return value as any;
}

export function SystemNotificationMessageSeverityToJSONTyped(value: any, ignoreDiscriminator: boolean): SystemNotificationMessageSeverity {
    return value as SystemNotificationMessageSeverity;
}

