/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SystemNotificationMessageSeverity } from '../models/SystemNotificationMessageSeverity';
import { HttpFile } from '../http/http';

export class SystemNotificationMessageDto {
    'title': string | null;
    'body': string | null;
    'severity'?: SystemNotificationMessageSeverity;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string",
            "format": ""
        },
        {
            "name": "severity",
            "baseName": "severity",
            "type": "SystemNotificationMessageSeverity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SystemNotificationMessageDto.attributeTypeMap;
    }

    public constructor() {
    }
}


