/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserReferenceDto } from './UserReferenceDto';
import {
    UserReferenceDtoFromJSON,
    UserReferenceDtoFromJSONTyped,
    UserReferenceDtoToJSON,
    UserReferenceDtoToJSONTyped,
} from './UserReferenceDto';
import type { ProjectReferenceDto } from './ProjectReferenceDto';
import {
    ProjectReferenceDtoFromJSON,
    ProjectReferenceDtoFromJSONTyped,
    ProjectReferenceDtoToJSON,
    ProjectReferenceDtoToJSONTyped,
} from './ProjectReferenceDto';

/**
 * 
 * @export
 * @interface TeamFormDto
 */
export interface TeamFormDto {
    /**
     * 
     * @type {number}
     * @memberof TeamFormDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TeamFormDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TeamFormDto
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeamFormDto
     */
    completedProjects: number;
    /**
     * 
     * @type {number}
     * @memberof TeamFormDto
     */
    activeProjects: number;
    /**
     * 
     * @type {UserReferenceDto}
     * @memberof TeamFormDto
     */
    manager?: UserReferenceDto;
    /**
     * 
     * @type {Array<UserReferenceDto>}
     * @memberof TeamFormDto
     */
    members?: Array<UserReferenceDto> | null;
    /**
     * 
     * @type {Array<ProjectReferenceDto>}
     * @memberof TeamFormDto
     */
    projects?: Array<ProjectReferenceDto> | null;
}

/**
 * Check if a given object implements the TeamFormDto interface.
 */
export function instanceOfTeamFormDto(value: object): value is TeamFormDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('completedProjects' in value) || value['completedProjects'] === undefined) return false;
    if (!('activeProjects' in value) || value['activeProjects'] === undefined) return false;
    return true;
}

export function TeamFormDtoFromJSON(json: any): TeamFormDto {
    return TeamFormDtoFromJSONTyped(json, false);
}

export function TeamFormDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamFormDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'completedProjects': json['completedProjects'],
        'activeProjects': json['activeProjects'],
        'manager': json['manager'] == null ? undefined : UserReferenceDtoFromJSON(json['manager']),
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(UserReferenceDtoFromJSON)),
        'projects': json['projects'] == null ? undefined : ((json['projects'] as Array<any>).map(ProjectReferenceDtoFromJSON)),
    };
}

export function TeamFormDtoToJSON(json: any): TeamFormDto {
    return TeamFormDtoToJSONTyped(json, false);
}

export function TeamFormDtoToJSONTyped(value?: TeamFormDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'completedProjects': value['completedProjects'],
        'activeProjects': value['activeProjects'],
        'manager': UserReferenceDtoToJSON(value['manager']),
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(UserReferenceDtoToJSON)),
        'projects': value['projects'] == null ? undefined : ((value['projects'] as Array<any>).map(ProjectReferenceDtoToJSON)),
    };
}

