/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserMinimalDto } from './UserMinimalDto';
import {
    UserMinimalDtoFromJSON,
    UserMinimalDtoFromJSONTyped,
    UserMinimalDtoToJSON,
    UserMinimalDtoToJSONTyped,
} from './UserMinimalDto';

/**
 * 
 * @export
 * @interface TeamDto
 */
export interface TeamDto {
    /**
     * 
     * @type {number}
     * @memberof TeamDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TeamDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TeamDto
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeamDto
     */
    completedProjects: number;
    /**
     * 
     * @type {number}
     * @memberof TeamDto
     */
    activeProjects: number;
    /**
     * 
     * @type {UserMinimalDto}
     * @memberof TeamDto
     */
    manager?: UserMinimalDto;
    /**
     * 
     * @type {Array<UserMinimalDto>}
     * @memberof TeamDto
     */
    members?: Array<UserMinimalDto> | null;
}

/**
 * Check if a given object implements the TeamDto interface.
 */
export function instanceOfTeamDto(value: object): value is TeamDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('completedProjects' in value) || value['completedProjects'] === undefined) return false;
    if (!('activeProjects' in value) || value['activeProjects'] === undefined) return false;
    return true;
}

export function TeamDtoFromJSON(json: any): TeamDto {
    return TeamDtoFromJSONTyped(json, false);
}

export function TeamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'completedProjects': json['completedProjects'],
        'activeProjects': json['activeProjects'],
        'manager': json['manager'] == null ? undefined : UserMinimalDtoFromJSON(json['manager']),
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(UserMinimalDtoFromJSON)),
    };
}

export function TeamDtoToJSON(json: any): TeamDto {
    return TeamDtoToJSONTyped(json, false);
}

export function TeamDtoToJSONTyped(value?: TeamDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'completedProjects': value['completedProjects'],
        'activeProjects': value['activeProjects'],
        'manager': UserMinimalDtoToJSON(value['manager']),
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(UserMinimalDtoToJSON)),
    };
}

