/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserReferenceDto } from './UserReferenceDto';
import {
    UserReferenceDtoFromJSON,
    UserReferenceDtoFromJSONTyped,
    UserReferenceDtoToJSON,
    UserReferenceDtoToJSONTyped,
} from './UserReferenceDto';

/**
 * 
 * @export
 * @interface TeamDetailsDto
 */
export interface TeamDetailsDto {
    /**
     * 
     * @type {number}
     * @memberof TeamDetailsDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TeamDetailsDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TeamDetailsDto
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeamDetailsDto
     */
    completedProjects: number;
    /**
     * 
     * @type {number}
     * @memberof TeamDetailsDto
     */
    activeProjects: number;
    /**
     * 
     * @type {UserReferenceDto}
     * @memberof TeamDetailsDto
     */
    manager?: UserReferenceDto;
    /**
     * 
     * @type {Array<UserReferenceDto>}
     * @memberof TeamDetailsDto
     */
    members?: Array<UserReferenceDto> | null;
}

/**
 * Check if a given object implements the TeamDetailsDto interface.
 */
export function instanceOfTeamDetailsDto(value: object): value is TeamDetailsDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('completedProjects' in value) || value['completedProjects'] === undefined) return false;
    if (!('activeProjects' in value) || value['activeProjects'] === undefined) return false;
    return true;
}

export function TeamDetailsDtoFromJSON(json: any): TeamDetailsDto {
    return TeamDetailsDtoFromJSONTyped(json, false);
}

export function TeamDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'completedProjects': json['completedProjects'],
        'activeProjects': json['activeProjects'],
        'manager': json['manager'] == null ? undefined : UserReferenceDtoFromJSON(json['manager']),
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(UserReferenceDtoFromJSON)),
    };
}

export function TeamDetailsDtoToJSON(json: any): TeamDetailsDto {
    return TeamDetailsDtoToJSONTyped(json, false);
}

export function TeamDetailsDtoToJSONTyped(value?: TeamDetailsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'completedProjects': value['completedProjects'],
        'activeProjects': value['activeProjects'],
        'manager': UserReferenceDtoToJSON(value['manager']),
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(UserReferenceDtoToJSON)),
    };
}

