/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimesheetFullDto } from './TimesheetFullDto';
import {
    TimesheetFullDtoFromJSON,
    TimesheetFullDtoFromJSONTyped,
    TimesheetFullDtoToJSON,
    TimesheetFullDtoToJSONTyped,
} from './TimesheetFullDto';

/**
 * 
 * @export
 * @interface TimesheetFullDtoPaginated
 */
export interface TimesheetFullDtoPaginated {
    /**
     * 
     * @type {Array<TimesheetFullDto>}
     * @memberof TimesheetFullDtoPaginated
     */
    data: Array<TimesheetFullDto>;
    /**
     * 
     * @type {number}
     * @memberof TimesheetFullDtoPaginated
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof TimesheetFullDtoPaginated
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof TimesheetFullDtoPaginated
     */
    totalCount: number;
    /**
     * 
     * @type {number}
     * @memberof TimesheetFullDtoPaginated
     */
    pageSize: number;
    /**
     * 
     * @type {boolean}
     * @memberof TimesheetFullDtoPaginated
     */
    readonly hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TimesheetFullDtoPaginated
     */
    readonly hasNextPage: boolean;
}

/**
 * Check if a given object implements the TimesheetFullDtoPaginated interface.
 */
export function instanceOfTimesheetFullDtoPaginated(value: object): value is TimesheetFullDtoPaginated {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    return true;
}

export function TimesheetFullDtoPaginatedFromJSON(json: any): TimesheetFullDtoPaginated {
    return TimesheetFullDtoPaginatedFromJSONTyped(json, false);
}

export function TimesheetFullDtoPaginatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimesheetFullDtoPaginated {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TimesheetFullDtoFromJSON)),
        'currentPage': json['currentPage'],
        'totalPages': json['totalPages'],
        'totalCount': json['totalCount'],
        'pageSize': json['pageSize'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function TimesheetFullDtoPaginatedToJSON(json: any): TimesheetFullDtoPaginated {
    return TimesheetFullDtoPaginatedToJSONTyped(json, false);
}

export function TimesheetFullDtoPaginatedToJSONTyped(value?: Omit<TimesheetFullDtoPaginated, 'hasPreviousPage'|'hasNextPage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(TimesheetFullDtoToJSON)),
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'pageSize': value['pageSize'],
    };
}

