/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimesheetDetailsDto } from './TimesheetDetailsDto';
import {
    TimesheetDetailsDtoFromJSON,
    TimesheetDetailsDtoFromJSONTyped,
    TimesheetDetailsDtoToJSON,
    TimesheetDetailsDtoToJSONTyped,
} from './TimesheetDetailsDto';

/**
 * 
 * @export
 * @interface TimesheetDetailsDtoTimesheetResponse
 */
export interface TimesheetDetailsDtoTimesheetResponse {
    /**
     * 
     * @type {Date}
     * @memberof TimesheetDetailsDtoTimesheetResponse
     */
    serverTime: Date;
    /**
     * 
     * @type {TimesheetDetailsDto}
     * @memberof TimesheetDetailsDtoTimesheetResponse
     */
    timesheet: TimesheetDetailsDto;
}

/**
 * Check if a given object implements the TimesheetDetailsDtoTimesheetResponse interface.
 */
export function instanceOfTimesheetDetailsDtoTimesheetResponse(value: object): value is TimesheetDetailsDtoTimesheetResponse {
    if (!('serverTime' in value) || value['serverTime'] === undefined) return false;
    if (!('timesheet' in value) || value['timesheet'] === undefined) return false;
    return true;
}

export function TimesheetDetailsDtoTimesheetResponseFromJSON(json: any): TimesheetDetailsDtoTimesheetResponse {
    return TimesheetDetailsDtoTimesheetResponseFromJSONTyped(json, false);
}

export function TimesheetDetailsDtoTimesheetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimesheetDetailsDtoTimesheetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'serverTime': (new Date(json['serverTime'])),
        'timesheet': TimesheetDetailsDtoFromJSON(json['timesheet']),
    };
}

export function TimesheetDetailsDtoTimesheetResponseToJSON(json: any): TimesheetDetailsDtoTimesheetResponse {
    return TimesheetDetailsDtoTimesheetResponseToJSONTyped(json, false);
}

export function TimesheetDetailsDtoTimesheetResponseToJSONTyped(value?: TimesheetDetailsDtoTimesheetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serverTime': ((value['serverTime']).toISOString()),
        'timesheet': TimesheetDetailsDtoToJSON(value['timesheet']),
    };
}

