/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimesheetDto } from './TimesheetDto';
import {
    TimesheetDtoFromJSON,
    TimesheetDtoFromJSONTyped,
    TimesheetDtoToJSON,
    TimesheetDtoToJSONTyped,
} from './TimesheetDto';

/**
 * 
 * @export
 * @interface TimesheetDtoTimesheetResponse
 */
export interface TimesheetDtoTimesheetResponse {
    /**
     * 
     * @type {Date}
     * @memberof TimesheetDtoTimesheetResponse
     */
    serverTime: Date;
    /**
     * 
     * @type {TimesheetDto}
     * @memberof TimesheetDtoTimesheetResponse
     */
    timesheet: TimesheetDto;
}

/**
 * Check if a given object implements the TimesheetDtoTimesheetResponse interface.
 */
export function instanceOfTimesheetDtoTimesheetResponse(value: object): value is TimesheetDtoTimesheetResponse {
    if (!('serverTime' in value) || value['serverTime'] === undefined) return false;
    if (!('timesheet' in value) || value['timesheet'] === undefined) return false;
    return true;
}

export function TimesheetDtoTimesheetResponseFromJSON(json: any): TimesheetDtoTimesheetResponse {
    return TimesheetDtoTimesheetResponseFromJSONTyped(json, false);
}

export function TimesheetDtoTimesheetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimesheetDtoTimesheetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'serverTime': (new Date(json['serverTime'])),
        'timesheet': TimesheetDtoFromJSON(json['timesheet']),
    };
}

export function TimesheetDtoTimesheetResponseToJSON(json: any): TimesheetDtoTimesheetResponse {
    return TimesheetDtoTimesheetResponseToJSONTyped(json, false);
}

export function TimesheetDtoTimesheetResponseToJSONTyped(value?: TimesheetDtoTimesheetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serverTime': ((value['serverTime']).toISOString()),
        'timesheet': TimesheetDtoToJSON(value['timesheet']),
    };
}

