/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestCombinedMinimalDto } from '../models/RequestCombinedMinimalDto';
import { UserMinimalDto } from '../models/UserMinimalDto';
import { HttpFile } from '../http/http';

export class TimesheetFullDto {
    'id': string;
    'date': Date;
    'startTime'?: Date | null;
    'endTime'?: Date | null;
    'workMinutes'?: number | null;
    'requests'?: Array<RequestCombinedMinimalDto> | null;
    'user'?: UserMinimalDto;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "workMinutes",
            "baseName": "workMinutes",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "requests",
            "baseName": "requests",
            "type": "Array<RequestCombinedMinimalDto>",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UserMinimalDto",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TimesheetFullDto.attributeTypeMap;
    }

    public constructor() {
    }
}
