/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimesheetMinimalDto
 */
export interface TimesheetMinimalDto {
    /**
     * 
     * @type {string}
     * @memberof TimesheetMinimalDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof TimesheetMinimalDto
     */
    date: Date;
    /**
     * 
     * @type {Date}
     * @memberof TimesheetMinimalDto
     */
    startTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TimesheetMinimalDto
     */
    endTime?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof TimesheetMinimalDto
     */
    workMinutes?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof TimesheetMinimalDto
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the TimesheetMinimalDto interface.
 */
export function instanceOfTimesheetMinimalDto(value: object): value is TimesheetMinimalDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function TimesheetMinimalDtoFromJSON(json: any): TimesheetMinimalDto {
    return TimesheetMinimalDtoFromJSONTyped(json, false);
}

export function TimesheetMinimalDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimesheetMinimalDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': (new Date(json['date'])),
        'startTime': json['startTime'] == null ? undefined : (new Date(json['startTime'])),
        'endTime': json['endTime'] == null ? undefined : (new Date(json['endTime'])),
        'workMinutes': json['workMinutes'] == null ? undefined : json['workMinutes'],
        'isActive': json['isActive'],
    };
}

export function TimesheetMinimalDtoToJSON(json: any): TimesheetMinimalDto {
    return TimesheetMinimalDtoToJSONTyped(json, false);
}

export function TimesheetMinimalDtoToJSONTyped(value?: TimesheetMinimalDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date': ((value['date']).toISOString()),
        'startTime': value['startTime'] == null ? undefined : ((value['startTime'] as any).toISOString()),
        'endTime': value['endTime'] == null ? undefined : ((value['endTime'] as any).toISOString()),
        'workMinutes': value['workMinutes'],
        'isActive': value['isActive'],
    };
}

