/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPosition } from './UserPosition';
import {
    UserPositionFromJSON,
    UserPositionFromJSONTyped,
    UserPositionToJSON,
    UserPositionToJSONTyped,
} from './UserPosition';
import type { UserStatus } from './UserStatus';
import {
    UserStatusFromJSON,
    UserStatusFromJSONTyped,
    UserStatusToJSON,
    UserStatusToJSONTyped,
} from './UserStatus';

/**
 * 
 * @export
 * @interface UserReferenceDto
 */
export interface UserReferenceDto {
    /**
     * 
     * @type {string}
     * @memberof UserReferenceDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserReferenceDto
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof UserReferenceDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserReferenceDto
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserReferenceDto
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserReferenceDto
     */
    image?: string | null;
    /**
     * 
     * @type {UserPosition}
     * @memberof UserReferenceDto
     */
    userPosition?: UserPosition;
    /**
     * 
     * @type {UserStatus}
     * @memberof UserReferenceDto
     */
    userStatus: UserStatus;
}



/**
 * Check if a given object implements the UserReferenceDto interface.
 */
export function instanceOfUserReferenceDto(value: object): value is UserReferenceDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('userStatus' in value) || value['userStatus'] === undefined) return false;
    return true;
}

export function UserReferenceDtoFromJSON(json: any): UserReferenceDto {
    return UserReferenceDtoFromJSONTyped(json, false);
}

export function UserReferenceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserReferenceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userName': json['userName'],
        'email': json['email'] == null ? undefined : json['email'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'image': json['image'] == null ? undefined : json['image'],
        'userPosition': json['userPosition'] == null ? undefined : UserPositionFromJSON(json['userPosition']),
        'userStatus': UserStatusFromJSON(json['userStatus']),
    };
}

export function UserReferenceDtoToJSON(json: any): UserReferenceDto {
    return UserReferenceDtoToJSONTyped(json, false);
}

export function UserReferenceDtoToJSONTyped(value?: UserReferenceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userName': value['userName'],
        'email': value['email'],
        'fullName': value['fullName'],
        'phoneNumber': value['phoneNumber'],
        'image': value['image'],
        'userPosition': UserPositionToJSON(value['userPosition']),
        'userStatus': UserStatusToJSON(value['userStatus']),
    };
}

