/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDto } from './UserDto';
import {
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
    UserDtoToJSONTyped,
} from './UserDto';

/**
 * 
 * @export
 * @interface UserDtoPaginated
 */
export interface UserDtoPaginated {
    /**
     * 
     * @type {Array<UserDto>}
     * @memberof UserDtoPaginated
     */
    data: Array<UserDto>;
    /**
     * 
     * @type {number}
     * @memberof UserDtoPaginated
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof UserDtoPaginated
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof UserDtoPaginated
     */
    totalCount: number;
    /**
     * 
     * @type {number}
     * @memberof UserDtoPaginated
     */
    pageSize: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserDtoPaginated
     */
    readonly hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserDtoPaginated
     */
    readonly hasNextPage: boolean;
}

/**
 * Check if a given object implements the UserDtoPaginated interface.
 */
export function instanceOfUserDtoPaginated(value: object): value is UserDtoPaginated {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    return true;
}

export function UserDtoPaginatedFromJSON(json: any): UserDtoPaginated {
    return UserDtoPaginatedFromJSONTyped(json, false);
}

export function UserDtoPaginatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDtoPaginated {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UserDtoFromJSON)),
        'currentPage': json['currentPage'],
        'totalPages': json['totalPages'],
        'totalCount': json['totalCount'],
        'pageSize': json['pageSize'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function UserDtoPaginatedToJSON(json: any): UserDtoPaginated {
    return UserDtoPaginatedToJSONTyped(json, false);
}

export function UserDtoPaginatedToJSONTyped(value?: Omit<UserDtoPaginated, 'hasPreviousPage'|'hasNextPage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(UserDtoToJSON)),
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'pageSize': value['pageSize'],
    };
}

