/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPosition } from './UserPosition';
import {
    UserPositionFromJSON,
    UserPositionFromJSONTyped,
    UserPositionToJSON,
    UserPositionToJSONTyped,
} from './UserPosition';
import type { WorkScheduleDetailsDto } from './WorkScheduleDetailsDto';
import {
    WorkScheduleDetailsDtoFromJSON,
    WorkScheduleDetailsDtoFromJSONTyped,
    WorkScheduleDetailsDtoToJSON,
    WorkScheduleDetailsDtoToJSONTyped,
} from './WorkScheduleDetailsDto';
import type { UserStatus } from './UserStatus';
import {
    UserStatusFromJSON,
    UserStatusFromJSONTyped,
    UserStatusToJSON,
    UserStatusToJSONTyped,
} from './UserStatus';

/**
 * 
 * @export
 * @interface UserWorkScheduleDto
 */
export interface UserWorkScheduleDto {
    /**
     * 
     * @type {string}
     * @memberof UserWorkScheduleDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserWorkScheduleDto
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof UserWorkScheduleDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserWorkScheduleDto
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserWorkScheduleDto
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserWorkScheduleDto
     */
    image?: string | null;
    /**
     * 
     * @type {UserPosition}
     * @memberof UserWorkScheduleDto
     */
    userPosition?: UserPosition;
    /**
     * 
     * @type {UserStatus}
     * @memberof UserWorkScheduleDto
     */
    userStatus: UserStatus;
    /**
     * 
     * @type {WorkScheduleDetailsDto}
     * @memberof UserWorkScheduleDto
     */
    workSchedule: WorkScheduleDetailsDto;
}



/**
 * Check if a given object implements the UserWorkScheduleDto interface.
 */
export function instanceOfUserWorkScheduleDto(value: object): value is UserWorkScheduleDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('userStatus' in value) || value['userStatus'] === undefined) return false;
    if (!('workSchedule' in value) || value['workSchedule'] === undefined) return false;
    return true;
}

export function UserWorkScheduleDtoFromJSON(json: any): UserWorkScheduleDto {
    return UserWorkScheduleDtoFromJSONTyped(json, false);
}

export function UserWorkScheduleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWorkScheduleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userName': json['userName'],
        'email': json['email'] == null ? undefined : json['email'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'image': json['image'] == null ? undefined : json['image'],
        'userPosition': json['userPosition'] == null ? undefined : UserPositionFromJSON(json['userPosition']),
        'userStatus': UserStatusFromJSON(json['userStatus']),
        'workSchedule': WorkScheduleDetailsDtoFromJSON(json['workSchedule']),
    };
}

export function UserWorkScheduleDtoToJSON(json: any): UserWorkScheduleDto {
    return UserWorkScheduleDtoToJSONTyped(json, false);
}

export function UserWorkScheduleDtoToJSONTyped(value?: UserWorkScheduleDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userName': value['userName'],
        'email': value['email'],
        'fullName': value['fullName'],
        'phoneNumber': value['phoneNumber'],
        'image': value['image'],
        'userPosition': UserPositionToJSON(value['userPosition']),
        'userStatus': UserStatusToJSON(value['userStatus']),
        'workSchedule': WorkScheduleDetailsDtoToJSON(value['workSchedule']),
    };
}

