/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDetailsDto } from './UserDetailsDto';
import {
    UserDetailsDtoFromJSON,
    UserDetailsDtoFromJSONTyped,
    UserDetailsDtoToJSON,
    UserDetailsDtoToJSONTyped,
} from './UserDetailsDto';

/**
 * 
 * @export
 * @interface UserDetailsDtoPaginated
 */
export interface UserDetailsDtoPaginated {
    /**
     * 
     * @type {Array<UserDetailsDto>}
     * @memberof UserDetailsDtoPaginated
     */
    data: Array<UserDetailsDto>;
    /**
     * 
     * @type {number}
     * @memberof UserDetailsDtoPaginated
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof UserDetailsDtoPaginated
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof UserDetailsDtoPaginated
     */
    totalCount: number;
    /**
     * 
     * @type {number}
     * @memberof UserDetailsDtoPaginated
     */
    pageSize: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserDetailsDtoPaginated
     */
    readonly hasPreviousPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserDetailsDtoPaginated
     */
    readonly hasNextPage: boolean;
}

/**
 * Check if a given object implements the UserDetailsDtoPaginated interface.
 */
export function instanceOfUserDetailsDtoPaginated(value: object): value is UserDetailsDtoPaginated {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    return true;
}

export function UserDetailsDtoPaginatedFromJSON(json: any): UserDetailsDtoPaginated {
    return UserDetailsDtoPaginatedFromJSONTyped(json, false);
}

export function UserDetailsDtoPaginatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetailsDtoPaginated {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UserDetailsDtoFromJSON)),
        'currentPage': json['currentPage'],
        'totalPages': json['totalPages'],
        'totalCount': json['totalCount'],
        'pageSize': json['pageSize'],
        'hasPreviousPage': json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'],
    };
}

export function UserDetailsDtoPaginatedToJSON(json: any): UserDetailsDtoPaginated {
    return UserDetailsDtoPaginatedToJSONTyped(json, false);
}

export function UserDetailsDtoPaginatedToJSONTyped(value?: Omit<UserDetailsDtoPaginated, 'hasPreviousPage'|'hasNextPage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(UserDetailsDtoToJSON)),
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
        'totalCount': value['totalCount'],
        'pageSize': value['pageSize'],
    };
}

