/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Nationality } from './Nationality';
import {
    NationalityFromJSON,
    NationalityFromJSONTyped,
    NationalityToJSON,
    NationalityToJSONTyped,
} from './Nationality';

/**
 * 
 * @export
 * @interface UserProfileDto
 */
export interface UserProfileDto {
    /**
     * 
     * @type {number}
     * @memberof UserProfileDto
     */
    id?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileDto
     */
    birthDate?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfileDto
     */
    gender?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    permanentAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDto
     */
    contactAddress?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserProfileDto
     */
    yearsOfWork: number;
    /**
     * 
     * @type {Nationality}
     * @memberof UserProfileDto
     */
    nationality: Nationality;
}



/**
 * Check if a given object implements the UserProfileDto interface.
 */
export function instanceOfUserProfileDto(value: object): value is UserProfileDto {
    if (!('yearsOfWork' in value) || value['yearsOfWork'] === undefined) return false;
    if (!('nationality' in value) || value['nationality'] === undefined) return false;
    return true;
}

export function UserProfileDtoFromJSON(json: any): UserProfileDto {
    return UserProfileDtoFromJSONTyped(json, false);
}

export function UserProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'gender': json['gender'] == null ? undefined : json['gender'],
        'permanentAddress': json['permanentAddress'] == null ? undefined : json['permanentAddress'],
        'contactAddress': json['contactAddress'] == null ? undefined : json['contactAddress'],
        'yearsOfWork': json['yearsOfWork'],
        'nationality': NationalityFromJSON(json['nationality']),
    };
}

export function UserProfileDtoToJSON(json: any): UserProfileDto {
    return UserProfileDtoToJSONTyped(json, false);
}

export function UserProfileDtoToJSONTyped(value?: UserProfileDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'birthDate': value['birthDate'] == null ? undefined : ((value['birthDate'] as any).toISOString()),
        'gender': value['gender'],
        'permanentAddress': value['permanentAddress'],
        'contactAddress': value['contactAddress'],
        'yearsOfWork': value['yearsOfWork'],
        'nationality': NationalityToJSON(value['nationality']),
    };
}

