/* tslint:disable */
/* eslint-disable */
/**
 * WorkHub.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkTimeDto
 */
export interface WorkTimeDto {
    /**
     * 
     * @type {number}
     * @memberof WorkTimeDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof WorkTimeDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof WorkTimeDto
     */
    startTimeMorning: string;
    /**
     * 
     * @type {string}
     * @memberof WorkTimeDto
     */
    endTimeMorning: string;
    /**
     * 
     * @type {string}
     * @memberof WorkTimeDto
     */
    startTimeAfternoon: string;
    /**
     * 
     * @type {string}
     * @memberof WorkTimeDto
     */
    endTimeAfternoon: string;
    /**
     * 
     * @type {number}
     * @memberof WorkTimeDto
     */
    allowedLateMinutes: number;
}

/**
 * Check if a given object implements the WorkTimeDto interface.
 */
export function instanceOfWorkTimeDto(value: object): value is WorkTimeDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('startTimeMorning' in value) || value['startTimeMorning'] === undefined) return false;
    if (!('endTimeMorning' in value) || value['endTimeMorning'] === undefined) return false;
    if (!('startTimeAfternoon' in value) || value['startTimeAfternoon'] === undefined) return false;
    if (!('endTimeAfternoon' in value) || value['endTimeAfternoon'] === undefined) return false;
    if (!('allowedLateMinutes' in value) || value['allowedLateMinutes'] === undefined) return false;
    return true;
}

export function WorkTimeDtoFromJSON(json: any): WorkTimeDto {
    return WorkTimeDtoFromJSONTyped(json, false);
}

export function WorkTimeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkTimeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'startTimeMorning': json['startTimeMorning'],
        'endTimeMorning': json['endTimeMorning'],
        'startTimeAfternoon': json['startTimeAfternoon'],
        'endTimeAfternoon': json['endTimeAfternoon'],
        'allowedLateMinutes': json['allowedLateMinutes'],
    };
}

export function WorkTimeDtoToJSON(json: any): WorkTimeDto {
    return WorkTimeDtoToJSONTyped(json, false);
}

export function WorkTimeDtoToJSONTyped(value?: WorkTimeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'startTimeMorning': value['startTimeMorning'],
        'endTimeMorning': value['endTimeMorning'],
        'startTimeAfternoon': value['startTimeAfternoon'],
        'endTimeAfternoon': value['endTimeAfternoon'],
        'allowedLateMinutes': value['allowedLateMinutes'],
    };
}

